#ifndef __X86_64_MMAP_H__
#define __X86_64_MMAP_H__

#define SYSCALL_TRAP_NUMBER 123

#define P4_PTE_ADDRESSES 0x10000000000

#define MMAP_PHYSICAL_PAGES_START          0
#define MMAP_PHYSICAL_PAGES_END            P4_PTE_ADDRESSES

#define MMAP_KERNEL_STACKS_START           P4_PTE_ADDRESSES
#define MMAP_KERNEL_STACKS_END     (0x2  * P4_PTE_ADDRESSES)

#define MMAP_KERNEL_RSVD_START     (0x2  * P4_PTE_ADDRESSES)
#define MMAP_KERNEL_RSVD_END       (0xF  * P4_PTE_ADDRESSES)

#define MMAP_KERNEL_HEAP_START     (0xF  * P4_PTE_ADDRESSES)
#define MMAP_KERNEL_HEAP_END       (0x10 * P4_PTE_ADDRESSES)

#define MMAP_KERNEL_USER_START     (0x10 * P4_PTE_ADDRESSES)

#endif